---
log_format: '%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\" (%{ratio}n)'
log_path: "/Users/Rene/Desktop/TFG/stats-icecast/access.log"
seek_pos: 119489
last_line: 91.116.180.88 - - [13/Apr/2015:23:50:54 +0200] "GET /cuacfm.aac HTTP/1.1"
  200 2872018 "-" "Lavf52.111.0" 175
