---
log_format: '%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\" (%{ratio}n)'
log_path: "/Users/Rene/Desktop/TFG/stats-icecast/access.log"
seek_pos: 630362
last_line: 83.165.23.134 - - [30/Mar/2015:07:26:51 +0200] "GET /cuacfm.mp3 HTTP/1.1"
  200 94165 "http://cuacfm.org/directo/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0;
  rv:11.0) like Gecko" 5
