---
log_format: '%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\" (%{ratio}n)'
log_path: "/Users/Rene/Desktop/TFG/stats-icecast/access.log"
seek_pos: 759964
last_line: 68.227.245.105 - - [13/Apr/2015:07:34:17 +0200] "GET /cuacfm.aac HTTP/1.0"
  200 68303 "-" "NSPlayer/10.0.0.3702 WMFSDK/10.0" 0
